version: '3.8'

volumes:
  api:
    driver: local
    driver_opts: 
      o: bind
      type: none
      device: "./"


services:

  database:
    container_name: storedb
    image: rethinkdb
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "28015:28015"
    networks:
      - default

  redis:
    container_name: ${REDIS_NAME}  
    restart: unless-stopped
    image: redis:latest
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - default

  web:
    container_name: url_shortener
    build: 
      context: .
    env_file:
      - .env
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${APP_PORT} -b '0.0.0.0'"
    volumes:
      - api:/var/www
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
    networks:
      - default
    stdin_open: true
    tty: true
