version: '3.8'

volumes:
  api:
    driver: local
    driver_opts: 
      o: bind
      type: none
      device: "./"


services:

  database:
    container_name: storedb
    image: rethinkdb
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "28015:28015"
    networks:
      - default

  redis:
    container_name: ${REDIS_NAME}  
    restart: unless-stopped
    image: redis:latest
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - default

  web:
    container_name: url_shortener
    build: 
      context: .
    env_file:
      - .env
    command: bundle exec rdebug-ide --debug --host 0.0.0.0 --port ${APP_DEBUG_PORT} -- rails s -p ${APP_PORT} -b 0.0.0.0
    volumes:
      - api:/var/www
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_DEBUG_PORT}:${APP_DEBUG_PORT}"
      - "26162:26162"
    depends_on:
      - redis
    networks:
      - default
    stdin_open: true
    tty: true
