# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies, and  run linters
name: Install dependencies, run linters, and build test report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
    # Bulid Project
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          bundler-cache: true
      # Generate RSpec
      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@5e02d5a3e8dcbcb48e69a867c7a84993f749bf21
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: tmp/test_results.json
        if: always()
      # Tags Image
      - name: Rails Tagger
        uses: melheffe/rails_version_tagger@1.1.0
      # Add or Replace any other security checks here
      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/brakeman -q -w2
      # Add or Replace any other Linters here
      - name: Run linters
        run: |
          bin/rubocop --parallel
      - name: Test
        run: bundle exec rspec -f j -o tmp/test_results.json -f p
